version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      flask:
        patterns:
        - "*flask*"
        - "*Flask*"
      python-packages:
        patterns:
        - "*"
    ignore:
      - dependency-name: "pillow"
        # 11.0.0 seems to break vcsi
        versions: ["11"]