"""Add PB, FC, ENT tag maps

Revision ID: 017767fd9fdb
Revises: e8e3ef7a0fd7
Create Date: 2023-12-05 18:24:39.749539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017767fd9fdb'
down_revision = 'e8e3ef7a0fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ent_tags',
    sa.Column('stashtag_id', sa.Integer(), nullable=False),
    sa.Column('enttag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enttag_id'], ['gazelle_tags.id'], name=op.f('fk_ent_tags_enttag_id_gazelle_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stashtag_id'], ['stash_tag.id'], name=op.f('fk_ent_tags_stashtag_id_stash_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stashtag_id', 'enttag_id', name=op.f('pk_ent_tags'))
    )
    op.create_table('fc_tags',
    sa.Column('stashtag_id', sa.Integer(), nullable=False),
    sa.Column('fctag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fctag_id'], ['gazelle_tags.id'], name=op.f('fk_fc_tags_fctag_id_gazelle_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stashtag_id'], ['stash_tag.id'], name=op.f('fk_fc_tags_stashtag_id_stash_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stashtag_id', 'fctag_id', name=op.f('pk_fc_tags'))
    )
    op.create_table('pb_tags',
    sa.Column('stashtag_id', sa.Integer(), nullable=False),
    sa.Column('pbtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pbtag_id'], ['gazelle_tags.id'], name=op.f('fk_pb_tags_pbtag_id_gazelle_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stashtag_id'], ['stash_tag.id'], name=op.f('fk_pb_tags_stashtag_id_stash_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stashtag_id', 'pbtag_id', name=op.f('pk_pb_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pb_tags')
    op.drop_table('fc_tags')
    op.drop_table('ent_tags')
    # ### end Alembic commands ###
